export const theme = {
  colors: {
    primary: '#0047AB',
    primaryStrong: '#003584',
    background: '#F0F4F8',
    surface: '#FFFFFF',
    surfaceAlt: '#E4EBF2',
    text: '#142235',
    textMuted: '#51606F',
    border: '#B7C5D3',
    borderStrong: '#7C91A6',
    alert: '#FF6B00',
    success: '#2ECC71',
    warningInk: '#2C2114',
    shadow: 'rgba(6, 28, 61, 0.12)',
    gridDot: 'rgba(0, 71, 171, 0.14)',
  },
  spacing: {
    xxs: '4px',
    xs: '8px',
    sm: '16px',
    md: '24px',
    lg: '32px',
    xl: '40px',
  },
  radius: {
    sharp: '2px',
    panel: '4px',
  },
  typography: {
    sans: "'Inter', 'Segoe UI', sans-serif",
    mono: "'Space Mono', 'JetBrains Mono', monospace",
  },
  motion: {
    fast: '180ms',
    standard: '420ms',
    slow: '2000ms',
    staggerStep: '50ms',
    spring: '460ms cubic-bezier(0.22, 1, 0.36, 1)',
  },
};

export const themeVars = {
  '--td-color-primary': theme.colors.primary,
  '--td-color-primary-strong': theme.colors.primaryStrong,
  '--td-color-background': theme.colors.background,
  '--td-color-surface': theme.colors.surface,
  '--td-color-surface-alt': theme.colors.surfaceAlt,
  '--td-color-text': theme.colors.text,
  '--td-color-text-muted': theme.colors.textMuted,
  '--td-color-border': theme.colors.border,
  '--td-color-border-strong': theme.colors.borderStrong,
  '--td-color-alert': theme.colors.alert,
  '--td-color-success': theme.colors.success,
  '--td-color-warning-ink': theme.colors.warningInk,
  '--td-color-shadow': theme.colors.shadow,
  '--td-color-grid-dot': theme.colors.gridDot,
  '--td-space-xxs': theme.spacing.xxs,
  '--td-space-xs': theme.spacing.xs,
  '--td-space-sm': theme.spacing.sm,
  '--td-space-md': theme.spacing.md,
  '--td-space-lg': theme.spacing.lg,
  '--td-space-xl': theme.spacing.xl,
  '--td-radius-sharp': theme.radius.sharp,
  '--td-radius-panel': theme.radius.panel,
  '--td-font-sans': theme.typography.sans,
  '--td-font-mono': theme.typography.mono,
  '--td-motion-fast': theme.motion.fast,
  '--td-motion-standard': theme.motion.standard,
  '--td-motion-slow': theme.motion.slow,
  '--td-motion-stagger-step': theme.motion.staggerStep,
  '--td-motion-spring': theme.motion.spring,
};
