services:
  student-service:
    build:
      context: ./atomic-services/student
    container_name: teamder-student-service
    environment:
      PORT: 3001
      OUTSYSTEMS_BASE_URL: https://personal-0wtj3pne.outsystemscloud.com/Student/rest/Student
    ports:
      - "3001:3001"

  skill-service:
    build:
      context: ./atomic-services/skill
    container_name: teamder-skill-service
    environment:
      PORT: 3002
      SUPABASE_URL: ${SUPABASE_URL}
    ports:
      - "3002:3002"

  topic-service:
    build:
      context: ./atomic-services/project-topic
    container_name: teamder-project-topic-service
    environment:
      PORT: 3003
      SUPABASE_URL: ${SUPABASE_URL}
    ports:
      - "3003:3003"


